title: Student Worker Guide
description: A guide for students working in [Accessibility at Swarthmore](https://www.swarthmore.edu/accessibility)
- name: RSS Feed Fetch Action
                uses: Promptly-Technologies-LLC/rss-fetch-action@v2.1
            
            name: Fetch RSS Feed

on:
  push:
    branches:
      - main

jobs:
  fetch-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch RSS Feed
      uses: Promptly-Technologies-LLC/rss-fetch-action@v2
      with:
        feed_url: 'https://blogs.swarthmore.edu/its/category/accessibility/'
        file_path: './feed.json'
    
    - name: Commit and push changes to repository
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'Update RSS feed'
        file_pattern: '*.json'
